name       : hdparm
version    : 9.53
release    : 3
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.53.tar.gz : 2673f591df6916c6a1faec07069a7eb1cb8ee307615a615d808192fb0c0265e5
license    :
    - BSD-3-Clause
    - GPL-2.0
component  : system.utils
summary    : hdparm - get/set ATA/SATA drive parameters under Linux
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.
build      : |
    %make
install    : |
    %make_install

    install -m755 $workdir/contrib/idectl $installdir/sbin  
    install -m755 $workdir/contrib/ultrabayd $installdir/sbin

    install -D -m 0644 $workdir/wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -D -m 0755 $workdir/wiper/wiper.sh $installdir/usr/sbin/wiper.sh
