name       : hdparm
version    : '9.58'
release    : 7
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.58.tar.gz : 9ae78e883f3ce071d32ee0f1b9a2845a634fc4dd94a434e653fdbef551c5e10f
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : hdparm - get/set ATA/SATA drive parameters under Linux
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.
build      : |
    %make
install    : |
    %make_install

    install -m00755 contrib/idectl $installdir/sbin
    install -m00755 contrib/ultrabayd $installdir/sbin

    install -D -m00644 wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -D -m00755 wiper/wiper.sh $installdir/usr/sbin/wiper.sh
