name       : hdparm
version    : 9.52
release    : 2
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.52.tar.gz : c3429cd423e271fa565bf584598fd751dd2e773bb7199a592b06b5a61cec4fb6
license    : 
    - BSD-3-Clause
    - GPL-2.0
summary    : hdparm - get/set ATA/SATA drive parameters under Linux
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.    
build      : |
    %make
install    : |
    %make_install

    install -m755 $workdir/contrib/idectl $installdir/sbin  
    install -m755 $workdir/contrib/ultrabayd $installdir/sbin

    install -D -m 0644 $workdir/wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -D -m 0755 $workdir/wiper/wiper.sh $installdir/usr/sbin/wiper.sh
