name       : hdparm
version    : 9.56
release    : 5
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.56.tar.gz : 6ff9ed695f1017396eec4101f990f114b7b0e0a04c5aa6369c0394053d16e4da
license    :
    - BSD-3-Clause
    - GPL-2.0-only
component  : system.utils
summary    : hdparm - get/set ATA/SATA drive parameters under Linux
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.
build      : |
    %make
install    : |
    %make_install

    install -m00755 contrib/idectl $installdir/sbin
    install -m00755 contrib/ultrabayd $installdir/sbin

    install -D -m00644 wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -D -m00755 wiper/wiper.sh $installdir/usr/sbin/wiper.sh
