name       : hdparm
version    : '9.60'
release    : 8
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.60.tar.gz : 8397739c73e44d5ab96c4aef28fa9c0147276d53a1b5657ce04c4565cf6635cc
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later # For the apt.c file.
component  : system.utils
summary    : Tool to get/set ATA/SATA drive parameters
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.
build      : |
    %make
install    : |
    %make_install sbindir=/usr/sbin

    install -m00755 contrib/idectl $installdir/usr/sbin
    install -m00755 contrib/ultrabayd $installdir/usr/sbin

    install -Dm00644 wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -Dm00755 wiper/wiper.sh $installdir/usr/sbin/wiper.sh
