name       : hdparm
version    : '9.63'
release    : 10
source     :
    - https://freefr.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.63.tar.gz : 70785deaebba5877a89c123568b41dee990da55fc51420f13f609a1072899691
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later # For the apt.c file.
component  : system.utils
summary    : Tool to get/set ATA/SATA drive parameters
description: |
    hdparm is a command line utility to set and view hardware parameters of hard disk drives. It can also be used as a simple benchmarking tool.
build      : |
    %make
install    : |
    %make_install sbindir=/usr/sbin

    install -m00755 contrib/idectl $installdir/usr/sbin
    install -m00755 contrib/ultrabayd $installdir/usr/sbin

    install -Dm00644 wiper/README.txt $installdir/usr/share/doc/wiper/README.txt
    install -Dm00755 wiper/wiper.sh $installdir/usr/sbin/wiper.sh
