name       : hdparm
version    : 9.45
release    : 1
source     :
    - http://softlayer-sng.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.45.tar.gz : 23b01caa56a995cf0897877b6aff98ea622a5df255bc2894b1a7693387f38669
license    : BSD
summary    : hdparm
clang      : no
description: |
    hdparm - get/set ATA/SATA drive parameters under Linux
builddeps  :
setup      : |
build      : |
    %make
install    : |
    %make_install
